import type { Metadata } from "next";
import "./globals.css";
import { Sora } from "next/font/google";
import Providers from "@/libs/services/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sora.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
